# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  multicolor-sddm-theme = {
    pname = "multicolor-sddm-theme";
    version = "798507a2362459a6084d7c140c67c23702913c8c";
    src = fetchgit {
      url = "https://gitlab.com/dwt1/multicolor-sddm-theme";
      rev = "798507a2362459a6084d7c140c67c23702913c8c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-K6drHG564BDz4+iYZo14Pdd2gOMp+GXmxsUEnTu8DaI=";
    };
    date = "2022-10-17";
  };
  san-francisco-pro = {
    pname = "san-francisco-pro";
    version = "8bfea09aa6f1139479f80358b2e1e5c6dc991a58";
    src = fetchFromGitHub {
      owner = "sahibjotsaggu";
      repo = "San-Francisco-Pro-Fonts";
      rev = "8bfea09aa6f1139479f80358b2e1e5c6dc991a58";
      fetchSubmodules = false;
      sha256 = "sha256-mAXExj8n8gFHq19HfGy4UOJYKVGPYgarGd/04kUIqX4=";
    };
    date = "2021-06-22";
  };
}
