name: nvfetcher update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Daily

jobs:
  update-nvfetcher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v25

      - name: Update nvfetcher
        run: |
          pushd pkgs
          nix run github:berberman/nvfetcher
          popd

      - name: Manual Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Manual commit after nvfetcher update"
          git push

      - name: Create Pull Request
        run: |
          gh pr create --title "Manual Update" --body "Manually created commit after nvfetcher update" --base main --head "Nvfetcher/update"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
